// <auto-generated />
namespace CarRental.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SeedPlaces : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedPlaces));
        
        string IMigrationMetadata.Id
        {
            get { return "202003120853072_SeedPlaces"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
